name: Security Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  security-check:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/security-scan-v2.yml
